
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bukuagenda
    ports:
      - "3333:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway:/usr/src/app
    command: ["node", "server.js"]

  file-upload-service:
    build:
      context: ./backend/file-upload-service
    ports:
      - "3005:3005"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: bukuagenda
    depends_on:
      - mysql
    volumes:
      - ./backend/file-upload-service:/usr/src/app
      - ./backend/file-upload-service/uploads:/usr/src/app/uploads
    command: ["node", "server.js"]

  print-service:
    build:
      context: ./backend/print-service
    ports:
      - "3006:3006"
    volumes:
      - ./backend/print-service:/usr/src/app
    command: ["node", "server.js"]

  surat-keluar-service:
    build:
      context: ./backend/surat-keluar-service
    ports:
      - "3004:3004"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: bukuagenda
    depends_on:
      - mysql
    volumes:
      - ./backend/surat-keluar-service:/usr/src/app
    command: ["node", "server.js"]

  surat-masuk-service:
    build:
      context: ./backend/surat-masuk-service
    ports:
      - "3003:3003"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: bukuagenda
    depends_on:
      - mysql
    volumes:
      - ./backend/surat-masuk-service:/usr/src/app
    command: ["node", "server.js"]


  user-service:
    build:
      context: ./backend/user-service
    ports:
      - "3002:3002"
    volumes:
      - ./backend/user-service:/usr/src/app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: bukuagenda
      DB_PORT: 3306
    depends_on:
      - mysql
    command: ["node", "server.js"]

  frontend:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    user: root
    command: ["npm", "run", "serve"]
    volumes:
      - .:/usr/src/app

volumes:
  mysql-data: